"""
Moat Report Generator
Combines classification (Phase 0), report data (Phase 1), BM analysis (Phase 2),
and evidence-based scoring (Phase 3) into a comprehensive markdown report.
"""

import sys
import os
from datetime import datetime
from typing import Dict, Optional

class MoatReportGenerator:
    """Generates evidence-based moat analysis reports"""

    def generate_report(
        self,
        company_name: str,
        ticker: str,
        moat_evaluation: 'MoatEvaluation',
        bm_analysis: 'BMAnalysis',
        financials: Dict,
        report_url: str = ""
    ) -> str:
        """
        Create a detailed markdown report for the user.
        """
        
        # 1. Header
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        score_desc = self._get_score_description(moat_evaluation.moat_strength)
        
        lines = [
            f"# 🛡️ Evidence-Based Moat Analysis: {company_name} ({ticker})",
            f"",
            f"> **Date**: {timestamp}",
            f"> **Moat Score**: **{moat_evaluation.moat_strength}/5** ({score_desc})",
            f"> **Sector**: {moat_evaluation.classification.get('gics_sector', 'N/A')} > {moat_evaluation.classification.get('gics_industry', 'N/A')}",
            f"> **Evidence Based**: {'✅ Yes' if moat_evaluation.evidence_based else '❌ No (Estimation Only)'}",
            f"",
            f"---",
            f"",
        ]

        # 2. Executive Summary (The Top 3 Factors)
        lines.append(f"## 1. Executive Summary")
        top_moats = sorted(moat_evaluation.scores.items(), key=lambda x: x[1].score, reverse=True)[:3]
        
        if not top_moats or top_moats[0][1].score < 2:
             lines.append(f"이 기업은 현재 **뚜렷한 경제적 해자**가 확인되지 않았습니다. ({moat_evaluation.moat_strength}점)")
        else:
            lines.append(f"이 기업의 핵심 경쟁 우위는 다음과 같습니다:")
            for m_type, score in top_moats:
                kr_name = score.reasoning.split(':')[0] # simple parse
                lines.append(f"- **{kr_name} ({score.score}점)**: {score.reasoning}")

        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

        # 3. Business Model (6-Factor Decomposition)
        lines.append(f"## 2. Business Model (BM 6-Factors)")
        lines.append(f"DART 사업보고서 기반 기계적 분해 결과입니다. `[확인]` 라벨은 공시 텍스트에 근거함을 의미합니다.")
        lines.append(f"")
        
        bm_table = [
            "| Factor | Status | Analysis |",
            "|---|---|---|",
        ]
        
        factors = [
            ("1. Customer", bm_analysis.customer),
            ("2. Revenue Model", bm_analysis.revenue_model),
            ("3. Differentiation", bm_analysis.differentiation),
            ("4. Cost Structure", bm_analysis.cost_structure),
            ("5. Growth", bm_analysis.growth_condition),
            ("6. Failure Risk", bm_analysis.failure_condition),
        ]
        
        for name, elem in factors:
            if elem:
                status = "✅ 확인" if elem.label == "confirmed" else "⚠️ 추정"
                text = elem.answer.replace("\n", " ")
                if len(text) > 100: text = text[:100] + "..."
                bm_table.append(f"| **{name}** | {status} | {text} |")
            else:
                bm_table.append(f"| **{name}** | ❌ 미분석 | 데이터 부족 |")
                
        lines.extend(bm_table)
        lines.append(f"")
        lines.append(f"> **BM Completeness**: {bm_analysis.completeness:.0%} (Confirmed Elements)")
        lines.append(f"")

        # 4. Evidence Breakdown
        lines.append(f"## 3. Evidence & Verification")
        if moat_evaluation.verification_desc:
            lines.append(f"### 🔍 Verification for High Score (4+)")
            lines.append(f"```text")
            lines.append(moat_evaluation.verification_desc)
            lines.append(f"```")
        else:
             lines.append(f"해자 강도가 4점 미만이므로 '검증용 DESC' 생성이 생략되었습니다.")

        lines.append(f"")
        lines.append(f"### ⚠️ Data & Risks")
        if bm_analysis.failure_condition and "높음" in bm_analysis.failure_condition.answer:
             lines.append(f"- **Risk Alert**: {bm_analysis.failure_condition.answer}")
        
        debt = financials.get('debt_ratio')
        if debt and debt > 2.0:
            lines.append(f"- **Financial Warning**: Debt Ratio is {debt:.0%} (High Risk)")
            
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"*Report generated by Antigravity Stock Moat V2*")

        return "\n".join(lines)

    def _get_score_description(self, score: int) -> str:
        if score == 5: return "Wide Moat (Structural)"
        if score == 4: return "Strong Moat"
        if score == 3: return "Narrow Moat"
        if score == 2: return "Weak / Potential"
        return "None"

if __name__ == "__main__":
    # Test stub
    pass
